### ISSUE TITLE
will forever support io.js ?

### ISSUE THREAD

**Issue by Pana** [foreverjs/forever#668]
FYI

**Comment by tjtyrrell** [comment]
Since no one has answered you (and I found this through a different question I was hoping to find)... The short answer is yes... The way to do it is with the "-c" command option where you would change the command forever uses to execute the script.

Example:
forever -c iojs server.js

In Linux you can add a command alias:
alias foreverio='forever -c iojs'

This would allow you to run the command:
foreverio server.js

I can confirm it works with io.js.

The question I was hoping for is, can a forever option be exposed to change the default command?

**Comment by indexzero** [comment]
@tjtyrrell @Pana yes, but the answer is more complex than that. The base `bin/forever` script is:

```
#!/usr/bin/env node
require('../lib/forever').cli.start();
```

since the default `iojs` installation installs a symlink from the `iojs` binary to the `node` binary this won't break even if you just have `iojs` installed. This is something that affects all CLI apps and not just `forever`, but `iojs` is here to help :+1:

**Comment by tjtyrrell** [comment]
@indexzero Good to know, thank you!
