### ISSUE TITLE
-w flag doesn't register file changes inside virtual box

### ISSUE THREAD

**Issue by jamesaspence** [foreverjs/forever#744]
Using nodeJS v0.10.37 and forever 0.15.1. Running `forever start -w app.js` completely ignores any changes I make to app.js. I've tried specifying relative path, absolute path, using `--watchDirectory=`, `--watch true`, etc. etc.

The only way I could get the file to register was by specifying `forever --watch true start app.js`, on my macbook itself (rather than the virtualbox I was using). That registered the file changes correctly, allowing me to continue work. However, nothing seems to work on the virtualbox (Ubuntu 14.04).

**Comment by diogogmt** [comment]
I'm observing the same issue when running forever on a docker container with Ubuntu 14.04
node version: 0.12.7
forever version: 0.15.1

It works fine on my mac.

**Comment by diogogmt** [comment]
Initially I thought the problem could be caused by the fact my app was running inside a docker container.
However, I was able to reproduce by simply creating a virtual box centos VM and doing a NFS share with my mac.
If I modify the files through my mac forever doesn't restart the process, if I modify the files inside the VM forever restarts the process.

Could this issue be related to the fact that forever is not receiving any file change events from the mac since they are not being bubbled up to the VM?
Anybody have tried a different hypervisor, maybe vm-ware fusion or parallels?

@indexzero since chokidar is the lib watching the file system for changes, should this ticket be moved to their issue tracker?

**Comment by diogogmt** [comment]
Looks like it is a [virtual box limitation](https://www.virtualbox.org/ticket/10660)

**Comment by vinogradov** [comment]
Right, it is actually a [virtual box limitation](https://www.virtualbox.org/ticket/10660). It can be simply solved by polling. And `forever-monitor` [supports polling](https://github.com/foreverjs/forever-monitor/pull/110). But unfortunately for now `forever` depends on the old version of `forever-monitor` without polling support. So it can be solved by migrating `forever` to `forever-monitor 1.7.0` or by using [pm2](https://github.com/Unitech/pm2) which is also supports polling.

**Comment by jamesaspence** [comment]
Closing this due to it being answered a long time ago.
